#!/bin/sh
#
# Copyright 2018 Daniel Ellard
#
# Apache 2.0 License
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

# Script for installing a no-frills Trac, using Sqlite for
# storage, and using the built-in web server (instead of
# integrating it into a web server like Apache2).
#
# Note that Ubuntu repos already have a Trac package that
# is effortless to install via apt, but I'm not using it
# because it's a considerably older version of Trac, and
# I prefer the newer versions.  YMMV.

# TRACVERSION: the version of Trac to install
# BUILDDIR: scratch directory used for building
#
# get the stable release (currently 1.2.2)
TRACVERSION=1.2.2
BUILDDIR="/tmp/trac-build-$$"

# Refuse to continue if Trac is already installed
#
if [ -x /usr/local/bin/tracd ]; then
    echo "ERROR: Trac is already installed"
    /usr/local/bin/tracd --version
    exit 1
fi

# Make sure all the prerequisite packages are installed.
#
# Note: you might also add subversion, if you have users that
# require it.
#
# Note: we install apache2-utils, even though we're not going
# to use apache2, because it includes htdigest, a useful tool
# for setting up user passwords.
#
sudo apt install -yf python2.7-dev python2.7-setuptools \
	python-babel=1.3+dfsg.1-6 python-docutils \
	python-genshi python-pygments python-tz \
	apache2-utils git wget

# Now fetch the Trac software, built it, and install it.
#
rm -rf "${BUILDDIR}"
mkdir -p "${BUILDDIR}"
cd "${BUILDIR}"

wget "https://download.edgewall.org/trac/Trac-$TRACVERSION.tar.gz"

tar zxf "Trac-$TRACVERSION.tar.gz"
rm "Trac-$TRACVERSION.tar.gz"
cd "Trac-$TRACVERSION"

sudo python ./setup.py install

# cleanup the build area
cd ..
rm -rf "${BUILDDIR}"

# check whether it worked:
#
if [ ! -x /usr/local/bin/tracd ]; then
    echo "ERROR: Trac did not install"
    exit 1
fi

exit 0
