#!/bin/sh
#
# Copyright 2018 Daniel Ellard
#
# Apache 2.0 License
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

# Create a basic systemd service for Trac, for the first Trac
# project on this system.
#

if [ $# -ne 3 ]; then
    echo "Error: usage: $0 TracDataDirectory ProjectName Port"
    exit 1
fi

TRACDATADIR="${1}"
TRACPROJECT="${2}"
TRACPORT="${3}"

PROJDIR="${TRACDATADIR}/${TRACPROJECT}"

# check whether Trac is installed in the expected place
#
# Note: could also check that Trac is the expected version,
# but we don't
#
if [ ! -x /usr/local/bin/tracd ]; then
    echo "ERROR: Trac is not installed"
    exit 1
fi

if [ ! -d "${PROJDIR}" ]; then
    echo "ERROR: project directory $PROJDIR does not exist"
    exit 1
fi

if [ -f "/etc/systemd/system/trac.service" ]; then
    echo "ERROR: trac service already configured"
    exit 1
fi

cat << . | sudo tee /etc/systemd/system/trac.service
[Unit]
Description = TrackD Daemon
After = network.target

[Service]
ExecStart = /usr/local/bin/tracd \
	-p "$TRACPORT" --protocol=http11 \
	--auth="${TRACPROJECT},${PROJDIR}/.htdigest,Restricted" \
	-s "${PROJDIR}"
Type = simple
User = ${USER}
Group = $(id -g)

[Install]
WantedBy = multi-user.target
.

sudo systemctl enable trac
sudo systemctl restart trac
